---
# yaml-language-server: $schema=https://raw.githubusercontent.com/release-drafter/release-drafter/refs/heads/master/schema.json
# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
name-template: '$RESOLVED_VERSION 🌈'
tag-template: '$RESOLVED_VERSION'
template: |
  # :mega: openapipages $RESOLVED_VERSION released!

  We are pleased to announce the release of openapipages $RESOLVED_VERSION.

  ## :green_book: What's Changed

  $CHANGES

  ## :bow: Credits

  Special thanks to the following contributors who helped with this release: $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...$RESOLVED_VERSION

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
exclude-contributors:
  - 'dependabot'
  - 'pre-commit-ci'
  - 'renovate'
exclude-labels:
  - 'skip-changelog'
  - 'invalid'
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645942909
  - search: '/(?:and )?@(pre-commit-ci|dependabot|renovate)(?:\[bot\])?,?/g'
    replace: ''
autolabeler:
  - label: 'documentation'
    files:
      - '*.md'
      - 'docs/**'
    branch:
      - '/docs{0,1}\/.+/'
  - label: 'bug'
    branch:
      - '/fix\/.+/'
    title:
      - '/^fix/i'
  - label: 'enhancement'
    branch:
      - '/feature\/.+/'
    body:
      - '/JIRA-[0-9]{1,4}/'
    title:
      - '/^feat/i'
  - label: 'dependencies'
    title:
      - '/^chore\(deps\)/i'
      - '/^fix\(deps\)/i'
      - '/^chore:\s*bump/i'
  - label: 'github_actions'
    files:
      - '.github/workflows/*.yml'
  - label: 'chore'
    branch:
      - '/docs{0,1}\/.+/'
    title:
      - '/^chore/i'
