---
# Configuration for Release Drafter: https://github.com/release-drafter/release-drafter
name-template: '$NEXT_PATCH_VERSION 🌈'
tag-template: '$NEXT_PATCH_VERSION'
template: |
  # :mega: openapipages $NEXT_PATCH_VERSION released!

  We are pleased to announce the release of openapipages $NEXT_PATCH_VERSION.

  ## :green_book: What’s Changed

  $CHANGES

  ## :bow: Credits

  Special thanks to the following contributors who helped with this release: $CONTRIBUTORS

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$NEXT_PATCH_VERSION

change-template: '- $TITLE (#$NUMBER) @$AUTHOR'
no-changes-template: '- No changes'
prerelease-identifier: 'rc'
exclude-contributors:
  - 'dependabot'
  - 'pre-commit-ci'
  - 'renovate'
exclude-labels:
  - 'skip-changelog'
  - 'invalid'
replacers:
  # https://github.com/release-drafter/release-drafter/issues/569#issuecomment-645942909
  - search: '/(?:and )?@(pre-commit-ci|dependabot|renovate)(?:\[bot\])?,?/g'
    replace: ''
