---
name-template: '$RESOLVED_VERSION ðŸŒˆ'
tag-template: '$RESOLVED_VERSION'
template: |
  # What's Changed

  $CHANGES

  **Full Changelog**: https://github.com/$OWNER/$REPOSITORY/compare/$PREVIOUS_TAG...v$RESOLVED_VERSION

change-template: '- $TITLE by @$AUTHOR in #$NUMBER'
change-title-escapes: '\<*_&' # You can add # and @ to disable mentions, and add ` to disable code blocks.
exclude-contributors:
  - 'dependabot'
  - 'pre-commit-ci'

categories:
  - title: 'ðŸ’¥ Breaking'
    label: 'breaking'
  - title: 'ðŸš€ Features'
    labels:
      - 'feature'
      - 'enhancement'
  - title: 'ðŸ› Bug Fixes'
    labels:
      - 'fix'
      - 'bugfix'
      - 'bug'
  - title: 'ðŸ§° Maintenance'
    label: 'maintenance'
  - title: 'ðŸ“œ Documentation'
    label: 'docs'
  - title: 'ðŸ”§ Other changes'
    label: 'other'
  - title: 'â¬†ï¸ Dependencies'
    collapse-after: 3
    labels:
      - 'dependencies'


version-resolver:
  major:
    labels:
      - 'major'
      - 'breaking'
  minor:
    labels:
      - 'minor'
      - 'feature'
  patch:
    labels:
      - 'patch'
      - 'bug'
      - 'maintenance'
      - 'docs'
      - 'dependencies'
      - 'security'
  default: patch


exclude-labels:
  - 'skip-changelog'
