# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
---
_commit: v1.5.4
_src_path: https://github.com/hasansezertasan/copier-pyproject.git
async_style: asyncio
author_email: hasansezertasan@gmail.com
author_family_names: Taşan
author_full_name: Hasan Sezer Taşan
author_given_names: Hasan Sezer
github_repo_name: openapipages
github_user: hasansezertasan
include_ai_rulez: false
include_all_contributors: false
include_benchmarks: false
include_c_extensions: false
include_cli: false
include_compiler: false
include_dbeaver: false
include_docs: false
include_examples: true
include_freezer: false
include_gui: false
include_launcher: false
include_mcp: false
include_megalinter: false
include_postgres: false
include_profiling: false
include_pydantic_settings: false
include_redis: false
include_repo_ruleset: true
include_repo_settings: true
include_smokeshow: false
include_sonarcloud: false
include_sourcery: false
include_tui: false
include_vpn: false
include_web: false
include_worker: false
package_keywords: fastapi, flask, litestar, openapi, swagger, swagger-ui, scalar,
    elements, redoc, rapidoc, api, documentation, specification, spec
preset: library
repository_topics: ''
short_description: OpenAPI Spec-based pages (SwaggerUI, ReDoc, RapiDoc, Elements,
    Scalar) ready with configuration features.
