name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    name: Publish release
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version-file: '.python-version'
          cache: "pip"
      - name: Install Dependencies
        run: pip install hatch
      - name: Build
        run: hatch build
      - name: Publish
        env:
          HATCH_INDEX_USER: __token__
          HATCH_INDEX_AUTH: ${{ secrets.PYPI_TOKEN }}
        run: hatch publish
